# gu_toolkit: Efficient Guide, Compendium, and Applications

This notebook is an opinionated, practical guide for everyday toolkit use. It is organized for **fast onboarding** and **copy/paste utility**.

## How to use this notebook
1. Run the setup cell.
2. Jump to the section you need (quickstart, recipes, applications).
3. Copy a pattern and adapt it.

---

## Contents
- Quickstart
- Frequently used APIs (compendium)
- Parameter and numeric-expression patterns
- Introspection and debugging helpers
- Cool applications (interactive demos)

In [6]:
!pip -q install plotly pandas scipy numpy sympy anywidget

In [3]:
# Setup: Import toolkit
import conftest # helps find the src
from gu_toolkit import *

# 1) Quickstart

## Minimal interactive figure

In [4]:
fig = Figure(x_range=(-8, 8))
display(fig)

with fig:
    set_title("Quickstart: Interactive sine")
    plot(a * sin(b * x), x, label=r"$a \sin(b x)$")

OneShotOutput()

## Figure with some configuration

In [5]:
fig = Figure(x_range=(-3 * pi, 3 * pi))
display(fig)

with fig:
    set_title("Quickstart: Interacting sine waves")
    plot(
        sin(b[1] * x),
        x,
        label=r"$\sin(b_1x)$",
        color="blue",
        opacity=0.075,
        thickness=5,
    )
    plot(
        sin(b[2] * x),
        x,
        label=r"$\sin(b_2x)$",
        color="green",
        alpha=0.075,
        width=5,
    )
    # alpha is an alias for opacity, width is an alias for thickness
    plot(
        sin(b[1] * x) * sin(b[2] * x),
        x,
        label=r"$\sin(b_1x) \sin(b_2x)$",
        color="red",
        opacity=1,
    )
    # color can be specified as a name or a hex value
    parameter(b[1], value=1, min=1, max=20, step=1)
    parameter(b[2], value=2, min=1, max=20, step=1)

OneShotOutput()

## Plotting a purely numeric function or a python callable

The callable-first API supports plain Python functions as long as they can evaluate over NumPy arrays.

In [6]:
fig_callable = Figure(x_range=(-6, 6), y_range=(-1.5, 1.5), sampling_points=500)
display(fig_callable)

with fig_callable:
    set_title("Numeric callable: damped oscillation")

    def damped_wave(x):
        return np.exp(-0.15 * x**2) * np.cos(3 * x)

    # For single-variable callables, pass the plotting symbol as the second argument.
    plot(damped_wave, x, color="teal", label=r"$\exp(-0.15x^2) \cos(3x)$")

OneShotOutput()

The callable-first API accepts a Python function as the first argument and the plotting symbol as the second argument.

This pattern is useful when your model is already written numerically (NumPy/JAX style) and you still want gu_toolkit slider and layout features.

In [7]:
fig_callable_params = Figure(x_range=(-8, 8), y_range=(-2.5, 2.5), sampling_points=600)
display(fig_callable_params)

with fig_callable_params:
    set_title("Callable with explicit vars + sliders")
    # Use NumPy math inside numeric callables so array inputs evaluate correctly.
    plot(
        lambda x, A, k: A * np.sin(k * x),
        x,
        vars=(x, A, k),
        id="param-wave",
        label=r"$A*\sin(k x)$",
        color="orange",
    )
    # For multi-argument callables, declare vars=(...) so slider-backed parameters map explicitly.
    plot(
        lambda x, A, k: A + k * x,
        x,
        vars={"x": x, "A": A, "k": k[1]},
        id="param-line",
        label=r"$A+k_1 x$",
        color="blue",
    )
    parameter(A, value=1.2, min=0.0, max=2.5, step=0.1)
    parameter(k, value=1.0, min=0.5, max=4.0, step=0.1)

OneShotOutput()

Tip: for numeric callables, prefer NumPy functions (for example, <code>np.sin</code>) rather than SymPy functions (such as <code>sin</code>).

SymPy functions expect symbolic inputs, while callable plotting evaluates on NumPy arrays during rendering.

## Adding non-trivial info cards

Info cards can mix static HTML with dynamic callback segments that re-evaluate on render and slider changes.
Use this pattern to show diagnostics, derived metrics, and runtime context next to your plot.

Info cards let you attach rich, always-visible context to the figure panel. Use them for interpretation notes, formulas, and operating instructions so users can understand controls without leaving the notebook.

Practical guidance:
- Keep one card for *how to interact* (which slider controls what).
- Keep one card for *what to look for* (expected shape changes, limits, or invariants).
- Prefer short HTML snippets (`<b>`, `<code>`, `<br>`) so cards remain compact in narrow sidebars.

In [8]:
fig_info = Figure(x_range=(-2 * sp.pi, 2 * sp.pi), y_range=(-3, 3), sampling_points=600)
display(fig_info)

with fig_info:
    set_title("Quickstart: plot + diagnostics info cards")
    plot(a * sin(b * x), x, label=r"$a\sin(bx)$", color="royalblue")
    parameter(a, value=1.0, min=0.2, max=2.0, step=0.1)
    parameter(b, value=1.0, min=0.5, max=4.0, step=0.1)

    info(
        """
    <b>Tips</b><br>
    • Move <code>a</code> to scale amplitude.<br>
    • Move <code>b</code> to change frequency.<br>
    """,
        id="usage-tips",
    )

    def diagnostics_card(fig, ctx):
        p = fig.parameters.snapshot()
        amp = p[a]
        freq = p["b"]
        period = (2 * np.pi / freq) if freq else float("inf")
        est_energy = 0.5 * amp**2
        return (
            f"<b>Wave diagnostics</b><br>"
            f"reason: <code>{ctx.reason}</code><br>"
            f"a={amp:.2f}, b={freq:.2f}<br>"
            f"period≈{period:.3f}, $a^{{2}}/2$≈{est_energy:.3f}"
        )

    info(["<hr>", diagnostics_card], id="wave-diagnostics")
# parameters.snapshot() returns a symbol-keyed mapping; access values with the same symbols you registered.

OneShotOutput()

## Using multiple tabs

In [9]:
fig_tabs = Figure(x_range=(-6, 6), y_range=(-3, 3), sampling_points=400)
fig_tabs.add_view("phase", x_range=(-2 * pi, 2 * pi), y_range=(-3, 3), x_label="phase")
display(fig_tabs)

with fig_tabs:
    parameter(a, value=1.0, min=0.0, max=2.0, step=0.1)
    parameter(b, value=0.5, min=-2.0, max=2.0, step=0.1)

    plot(a * sin(x) + b, x, label=r"$a \sin(x)+b$", view=("main", "phase"), color="crimson")
    with fig_tabs.view("phase"):
        plot(cos(2 * x), x, label=r"$\cos(2x)", color="purple")

    info("<b>Shared card:</b> visible on every view", id="shared-card")
    info("<b>Phase note:</b> scoped to the phase tab", id="phase-card", view="phase")

OneShotOutput()

## Numerical integration

In [10]:
@NamedFunction
def Sq(x):
    return sign(sin(2*pi*x))

In [18]:
@NamedFunction
def Tr(x):
    return asin(sin(2*pi*x))/(pi/2)

In [20]:
fig=Figure()
fig.x_range=(-1,1)
display(fig)
with fig:
    plot(Sq(x),x,label=r"$\mathrm{Sq}(x)$")
    plot(Tr(x),x,label=r"$\mathrm{Tr}(x)$")

OneShotOutput()

In [21]:
fig=Figure()
fig.x_range=(-1,1)
display(fig)
with fig:
    plot(Tr(x),x,label=r"$\mathrm{Tr}(x)$")

OneShotOutput()

In [14]:
Nmax=100
a=np.zeros(Nmax+1)
for n in range(1, Nmax + 1):
    a[n]=NIntegrate(2*Sq(x)*sin(2*pi*n*x),(x,-1/2,1/2))/1.3

C:\Users\guraltsev\Documents\notebooks\gu_toolkit\src\gu_toolkit\numeric_operations.py:107: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze
  the integrand in order to determine the difficulties.  If the position of a
  local difficulty can be determined (singularity, discontinuity) one will
  probably gain from splitting up the interval and calling the integrator
  on the subranges.  Perhaps a special-purpose integrator should be used.

In [15]:
import numpy as np
import pandas as pd
from IPython.display import display, Markdown



if a.ndim == 1:
    df = pd.DataFrame({"harmonic": np.arange(a.size), "Coefficient": a})
elif a.ndim == 2 and a.shape[1] == 2:
    df = pd.DataFrame(a, columns=["harmonic", "Coefficient"])
else:
    raise ValueError(f"arr must be 1D (coeffs) or 2D with shape (N, 2); got {a.shape}")

display(Markdown("### Square wave"))
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(df)

### Square wave

     harmonic   Coefficient
0           0  0.000000e+00
1           1  9.794150e-01
2           2 -1.118793e-17
3           3  3.264717e-01
4           4 -1.292486e-16
5           5  1.958830e-01
6           6  6.166023e-17
7           7  1.399164e-01
8           8 -3.482613e-16
9           9  1.088239e-01
10         10 -1.024009e-17
11         11  8.903773e-02
12         12  1.521439e-16
13         13  7.533962e-02
14         14 -6.056887e-16
15         15  6.529434e-02
16         16  2.334488e-16
17         17  5.761265e-02
18         18  6.494319e-17
19         19  5.154816e-02
20         20 -5.455126e-16
21         21  4.663881e-02
22         22  7.370810e-16
23         23  4.258326e-02
24         24  3.062856e-16
25         25  3.917660e-02
26         26 -7.944378e-16
27         27  3.627463e-02
28         28 -1.541306e-16
29         29  3.377293e-02
30         30  2.872890e-15
31         31  3.159403e-02
32         32 -1.675686e-16
33         33  2.967924e-02
34         34  1.610469e-15
35         35  2.798329e-02
36         36 -1.076080e-15
37         37  2.647068e-02
38         38 -4.442548e-16
39         39  2.511321e-02
40         40  8.753953e-16
41         41  2.388817e-02
42         42 -1.691883e-16
43         43  2.277709e-02
44         44  4.192153e-15
45         45  2.176478e-02
46         46 -7.338008e-17
47         47  2.083862e-02
48         48 -7.332177e-16
49         49  1.998806e-02
50         50  2.500892e-16
51         51  1.920422e-02
52         52  1.652438e-15
53         53  1.847953e-02
54         54  2.790360e-15
55         55  1.780755e-02
56         56 -2.236812e-15
57         57  1.718272e-02
58         58  1.383567e-15
59         59  1.660025e-02
60         60  4.561920e-15
61         61  1.605598e-02
62         62 -2.072013e-15
63         63  1.554627e-02
64         64 -1.737515e-15
65         65  1.506792e-02
66         66 -1.151439e-15
67         67  1.461813e-02
68         68  2.503387e-16
69         69  1.419442e-02
70         70  1.182528e-15
71         71  1.379458e-02
72         72 -1.064310e-15
73         73  1.341664e-02
74         74  6.718352e-16
75         75  1.305887e-02
76         76  1.088825e-15
77         77  1.271968e-02
78         78  3.125864e-15
79         79  1.239766e-02
80         80 -8.934388e-16
81         81  1.209154e-02
82         82  1.236523e-14
83         83  1.180018e-02
84         84 -3.922903e-16
85         85  1.152253e-02
86         86  2.654663e-15
87         87  1.125764e-02
88         88  2.990393e-15
89         89  1.100466e-02
90         90 -5.480556e-17
91         91  1.076280e-02
92         92 -9.473597e-16
93         93  1.053134e-02
94         94 -5.594347e-16
95         95  1.030963e-02
96         96  3.332383e-15
97         97  1.009706e-02
98         98 -1.070924e-15
99         99  9.893081e-03
100       100  4.740563e-16

In [200]:
Nmax=100
a=np.zeros(Nmax+1)
for n in range(1, Nmax + 1):
    a[n]=NIntegrate(2*Tr(x)*sin(2*pi*n*x),(x,-1/2,1/2))/1.3

C:\Users\guraltsev\Documents\notebooks\gu_toolkit\numeric_operations.py:166: IntegrationWarning:

The maximum number of subdivisions (50) has been achieved.
  If increasing the limit yields no improvement it is advised to analyze
  the integrand in order to determine the difficulties.  If the position of a
  local difficulty can be determined (singularity, discontinuity) one will
  probably gain from splitting up the interval and calling the integrator
  on the subranges.  Perhaps a special-purpose integrator should be used.

In [202]:
import numpy as np
import pandas as pd
from IPython.display import display, Markdown



if a.ndim == 1:
    df = pd.DataFrame({"harmonic": np.arange(a.size), "Coefficient": a})
elif a.ndim == 2 and a.shape[1] == 2:
    df = pd.DataFrame(a, columns=["harmonic", "Coefficient"])
else:
    raise ValueError(f"arr must be 1D (coeffs) or 2D with shape (N, 2); got {a.shape}")

display(Markdown("### Triangle wave"))
with pd.option_context("display.max_rows", None, "display.max_columns", None):
    display(df)

### Triangle wave

     harmonic   Coefficient
0           0  0.000000e+00
1           1  9.794150e-01
2           2  6.896853e-17
3           3 -1.088239e-01
4           4 -1.044840e-16
5           5  3.917660e-02
6           6  3.014693e-17
7           7 -1.998806e-02
8           8 -1.930847e-16
9           9  1.209154e-02
10         10  3.807584e-17
11         11 -8.094339e-03
12         12  1.585953e-16
13         13  5.795355e-03
14         14 -2.502622e-16
15         15 -4.352956e-03
16         16  2.137934e-16
17         17  3.388979e-03
18         18  1.048377e-17
19         19 -2.713061e-03
20         20 -4.056338e-16
21         21  2.220896e-03
22         22  1.010447e-15
23         23 -1.851446e-03
24         24 -1.513599e-16
25         25  1.567064e-03
26         26 -9.307621e-16
27         27 -1.343505e-03
28         28 -1.200762e-15
29         29  1.164584e-03
30         30  3.070819e-15
31         31 -1.019162e-03
32         32 -5.248981e-16
33         33  8.993710e-04
34         34  1.136198e-15
35         35 -7.995225e-04
36         36 -7.822460e-16
37         37  7.154237e-04
38         38  6.056733e-16
39         39 -6.439284e-04
40         40  7.713645e-16
41         41  5.826383e-04
42         42  1.146838e-16
43         43 -5.296999e-04
44         44  1.808891e-15
45         45  4.836617e-04
46         46  4.494577e-16
47         47 -4.433748e-04
48         48 -9.583767e-16
49         49  4.079196e-04
50         50  2.029185e-16
51         51 -3.765533e-04
52         52  1.497120e-15
53         53  3.486704e-04
54         54  5.098209e-15
55         55 -3.237736e-04
56         56 -2.421340e-15
57         57  3.014512e-04
58         58  8.333108e-16
59         59 -2.813603e-04
60         60  3.758562e-15
61         61  2.632129e-04
62         62 -1.496243e-15
63         63 -2.467662e-04
64         64 -8.565865e-16
65         65  2.318142e-04
66         66 -1.223824e-15
67         67 -2.181811e-04
68         68  1.391676e-15
69         69  2.057162e-04
70         70  7.794180e-16
71         71 -1.942898e-04
72         72 -9.853118e-16
73         73  1.837896e-04
74         74  1.186633e-15
75         75 -1.741182e-04
76         76 -2.315146e-16
77         77  1.651906e-04
78         78  3.254707e-15
79         79 -1.569324e-04
80         80 -1.904621e-15
81         81  1.492783e-04
82         82  1.216071e-14
83         83 -1.421709e-04
84         84  7.967752e-16
85         85  1.355592e-04
86         86  1.402187e-15
87         87 -1.293982e-04
88         88  3.536210e-15
89         89  1.236479e-04
90         90 -1.493267e-15
91         91 -1.182726e-04
92         92 -2.305989e-15
93         93  1.132403e-04
94         94 -1.144174e-15
95         95 -1.085224e-04
96         96  2.496705e-15
97         97  1.040934e-04
98         98 -8.503819e-16
99         99 -9.993011e-05
100       100  1.617781e-15

In [ ]:
play(sin(220*2*pi*x),(x,0,1))